name: Build and Push MkDocs Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'docker-images/mkdocs/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: mkdocs
      USERNAME: ${{ github.repository_owner }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install wget
      run: sudo apt-get update && sudo apt-get install -y wget

    - name: Prepare and Build Docker image
      run: |
        cd docker-images/mkdocs
        source config.sh
        mkdir -p files
        wget https://github.com/squidfunk/mkdocs-material/archive/refs/tags/$MATERIAL_VERSION.tar.gz -O files/mkdocs-material.tar.gz
        docker build . -t ghcr.io/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest --build-arg VERSION=$MATERIAL_VERSION

    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest
